### ISSUE TITLE
Authenticating a push?

### ISSUE THREAD

**Issue by aendra-rininsland** [kbjr/Git.php#14]
Hi!
My use case is as follows: a user specifies a repo, a branch, their Git username and password. The script then does a clone of that repo, adds a file to it, makes a commit, and pushes it back to origin.

I'm now stuck on the "pushes it back to origin" part -- is there any way of authenticating other than setting up public key or digest authentication?

Thanks!

**Comment by Benjamin-Bach** [comment]
Hi Markus,
Thanks again for your time.

Yes, I know that without having my configuration, it's not easy to help me more than you have already done.
I tried to re-start everything on two completely different servers, my local docker and a remote cloud. It does not work.
I tried to change the users, groups, permissions. It does not work.

I 'm dropping these "conventional" attempts and return to pragmatism .

Related to https://github.com/kbjr/Git.php/issues/14, I tested modifying the push() method. And it works.
For the moment, I have simply hardcoded
```
$ this->getRepo()->push('https://USERNAME:PASSWORD@github.com/USERNAME/REPO.git', $branch);
```
Instead of
```
$this->getRepo()->push('origin', $branch);
```
Obviously, this implies abandoning SSH authentication in favor of HTTPS.
Certainly much less secure but it works.

For my project, this level of security is sufficient, I think I will fork your repo to allow the user and the password to be injected from Kirby's options. Then I will change the arguments passed in the push and pull methods conditionally.
I'm not a fan of storing the password in the config file.
Maybe grabbing an environment variable would be a more secure way.

Anyway, if you think there is something interesting in this process for your module (allow https instead of ssh for easier authentication), let me know and I will try to do a PR.

Thanks again for your help Markus!
